version: 2.1
#version for yml file

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py

workflows:
  version: 2
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
